# This file was updated with the Mesa Configuration Tool on Mar 08 2024 20:48:05
# Changes to most things are ok and will be read by the Configuration Tool

[MESA]
VERSION = 2.1.2
BOARD = 7i95
BOARD_NAME = 7i95t
FIRMWARE = 7i95t_1pktv2d.bin
CARD_0 = None
CARD_1 = None

[EMC]
VERSION = 1.1
MACHINE = 7i95T XYZ
DEBUG = 0x00000000

[HM2]
DRIVER = hm2_eth
ADDRESS = 10.10.10.10

[DISPLAY]
DISPLAY = axis
PROGRAM_PREFIX = /home/cnc/linuxcnc/nc_files
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = COMMANDED
MAX_FEED_OVERRIDE = 1.2
MIN_LINEAR_VELOCITY = 0.5
DEFAULT_LINEAR_VELOCITY = 50.0
MAX_LINEAR_VELOCITY = 150.0
CYCLE_TIME = 0.1
INTRO_GRAPHIC = emc2.gif
INTRO_TIME = 0
LATHE = 1

[KINS]
KINEMATICS = trivkins coordinates=XZ
JOINTS = 2

[EMCIO]
EMCIO = iov2
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

[RS274NGC]
PARAMETER_FILE = parameters.var
SUBROUTINE_PATH = /home/cnc/linuxcnc/subroutines

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
SERVO_PERIOD = 1000000

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[TRAJ]
COORDINATES = XZ
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
MAX_LINEAR_VELOCITY = 100.0
NO_FORCE_HOMING = 1

[HAL]
HALUI = halui
HALFILE = main.hal

HALFILE = common-loadrt-addf.hal
HALFILE = mesa-io.hal
HALFILE = homing.hal
HALFILE = panel-buttons.hal
HALFILE = overrides.hal
HALFILE = axes-mpg.hal
# HALFILE = spindle-lincurve.hal
# HALFILE = spindle-orient.hal
HALFILE = custom.hal
# POSTGUI_HALFILE = weiler_postgui.hal
SHUTDOWN = shutdown.hal

[AXIS_X]
MAX_VELOCITY = 150.0
MAX_ACCELERATION = 1000.0
MIN_LIMIT = 0.0
MAX_LIMIT = 151.0

[JOINT_0]
CARD = 0
TAB = 0
AXIS = X
MAX_VELOCITY = 150.0
MAX_ACCELERATION = 1000.0
TYPE = LINEAR
SCALE = -2000
STEPGEN_MAX_VEL = 200
STEPGEN_MAX_ACC = 1500
DIRSETUP = 150
DIRHOLD = 150
STEPLEN = 150
STEPSPACE = 150
FERROR =  10
MIN_FERROR =  10
DEADBAND = 0
P = 50
I = 0
D = 0
FF0 = 0
FF1 = 0.81967
FF2 = 0
BIAS = 0
MAX_OUTPUT = 0
MAX_ERROR = 5
HOME = 130.0
MIN_LIMIT = 0.0
MAX_LIMIT = 151.0
HOME_OFFSET = 134.000000
HOME_SEARCH_VEL = 30.000000
HOME_LATCH_VEL = -2.00000
HOME_FINAL_VEL = 0.00000
HOME_USE_INDEX = YES

[AXIS_Z]
MAX_VELOCITY = 150.0
MAX_ACCELERATION = 1000.0
MIN_LIMIT = 0.0
MAX_LIMIT = 600.0

[JOINT_1]
CARD = 0
TAB = 1
AXIS = Z
MAX_VELOCITY = 150.0
MAX_ACCELERATION = 1000.0
TYPE = LINEAR
SCALE = 4000

STEPGEN_MAX_VEL = 200
STEPGEN_MAX_ACC = 1500
DIRSETUP = 150
DIRHOLD = 150
STEPLEN = 150
STEPSPACE = 150
FERROR =  20
MIN_FERROR =  10
DEADBAND = 1
P = 50
I = 0
D = 0
FF0 = 0
FF1 = 0.81967
FF2 = 0
BIAS = 0
MAX_OUTPUT = 0
MAX_ERROR = 10

MIN_LIMIT = 0.0
MAX_LIMIT = 600.0
HOME = 150.0
HOME_OFFSET = 150.000000
HOME_SEARCH_VEL = 20.000000
HOME_LATCH_VEL = -2.00000
HOME_FINAL_VEL = 0.000000
HOME_USE_INDEX = YES

[INPUTS]
# DO NOT change the inputs they are used by the configuration tool

[OUTPUTS]
# DO NOT change the outputs they are used by the configuration tool

[OPTIONS]
# DO NOT change the options they are used by the configuration tool
LOAD_CONFIG = False
INTRO_GRAPHIC = emc2.gif
INTRO_GRAPHIC_TIME = 0
MANUAL_TOOL_CHANGE = False
CUSTOM_HAL = False
POST_GUI_HAL = False
SHUTDOWN_HAL = False
HALUI = False
PYVCP = False
GLADEVCP = False
LADDER = True
BACKUP = False

[PLC]
LADDER_RUNGS = 0
LADDER_BITS = 0
LADDER_S32_OUTPUTS = 0
LADDER_EXPRESSIONS = 0
LADDER_FLOAT_INPUTS = 0
LADDER_FLOAT_OUTPUTS = 0
LADDER_SYMBOLS = 0
LADDER_COUNTERS = 0
LADDER_S32_INPUTS = 0
LADDER_HAL_OUTPUTS = 0
LADDER_TIMERS = 0
LADDER_IEC_TIMERS = 0
LADDER_MONOSTABLES = 0
LADDER_WORDS = 0
LADDER_HAL_INPUTS = 0
LADDER_SECTIONS = 0

[SSERIAL]
# DO NOT change the sserial they are used by the configuration tool
SS_CARD = 7i70

[SPINDLE_0]
P = 300
I = 0
D = 0
FF0 = 1
FF1 = 0
FF2 = 0
BIAS = 0
DEADBAND = 0
MAX_OUTPUT = 50
ENCODER_SCALE = -4096
OUTPUT_SCALE = 1
OUTPUT_MIN_LIMIT = -1
OUTPUT_MAX_LIMIT = 1
ACCELERATION 	= 3000

MAX_ERROR = 1
ORIENT_DELAY = 4
ORIENT_TOLERANCE = 1
